config/routes.rb
Comit::Application.routes.draw do

  post "early_access/create"

  match     ':year/:month/:day/:title.md' => 'post#markdown'                        # Post in Mardown
  match     ':year/:month/:day/:title'    => 'post#show'                            # Post in HTML
  match     'hook/:token'                 => 'blog#hook',      :via => :post        # Hook for Git repository pull
  match     'auth/:provider/callback'     => 'session#create'                       # Authentication callback for omniauth
  match     'signout'                     => 'session#destroy'                      # Sign out
  match     'user/dashboard'              => 'user#show'                            # User profile
  resources :user,                        only: [:update, :destroy]                 # User management
  resources :blog,                        only: [:create, :destroy, :edit, :update] # Blog management
  root to:  'blog#index'                                                            # Blog index

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_coming_soon.haml
.coming-soon
  .cs-form
    %p 
      Comit is not ready yet. 
      %br
      Drop me your email address to get in early !
    = form_for EarlyAccess.new, :url => early_access_create_path, remote: true do |f| 
      = f.text_field :email_address, onfocus: "if(this.value == 'Enter your email address...') { this.value = ''; }", value: 'Enter your email address...'
      %br
      = f.submit "Notify me when it's ready !"
  .cs-error
  .cs-thanks
    %p
      You will be notified when early access will open. See you soon !

app/views/welcome/_pricing.haml
#pricing.part
  .content
    %h1 One simple plan

    #pricing-plan
      #plan-title
        Personnal
      #plan-price
        $8
      #plan-per-month
        each month
      %ul#featured
        %li Unmetered number of blogs
        %li Unmetered traffic
    #description
      %h2 
        %b Free trial
      %p 
        You can use Comit for free for 
        %b 30 days without any credit card or engagment. 
        At the end of your trial, you will receive an email and will decide if Comit feet your needs or not.

      %a#start{href: '/auth/github'}
        Authenticate with Github to start publish your blog

%hr

app/views/welcome/landing.haml
#landing-page

  #welcome-screen.part
  
    %header
      .content
        #menu
          = link_to "How it work ?", '#how-it-work'
          = '-'
          / = link_to "Pricing", '#pricing'
          / = '-'
          = link_to "Sign in with Github", '/auth/github', class: 'focus'

    #banner
      .content
        .left
          %h1 Comit
          %h2 Your git repo is now a blog.
          #headline>
            %b Comit is an bloging platform backed by Git. 
            Write, commit and push your publications online.
            %b Comit use Markdown markup language 
            to convert your papers into blog posts.

          %ul.menu
            %li= link_to 'See an example of blog powered by Comit'
            %li= link_to 'How it work ?', '#how-it-work'
            / %li= link_to "Pricing", '#pricing'

          / %a.getting-started{href: '/auth/github'}
          /   Getting Online !
          / .note 30-day free trial, no credit card needed !

          = render 'welcome/coming_soon'

        .right
          #screen
            = image_tag 'octopus.png'

    %p#simple
      %code git add 2013-01-01-Happy_New_Year.md 
      >> 
      %code http://yoursubdomain.comit.io/2013/01/01/Happy_New_Year

  %hr

  #how-it-work.part
    .content
      %h1 
        = link_to 'How it work ?', '#how-it-work'

      #rules

        %h2 Your post are writed in Markdown

        %p Markup is a lightweiht markup already used in many online services (Hacker news, Github, Stack Overflow, etc...). It provide clear and readable synthax and is easy to learn.

        %h2 Your blog posts are stored on a public Git repository

        %p You own your data. You can easily migrate from Comit to another markdown supported blog platform (like Jekyll or Octopress).

        %h2 Your public Git repository is indexed by Comit

        %p 
          When you create your new blog on Comit, app clone your git repository and index it to find compatible markdown files. All files in the roots directory that respect the following name scheme (
          %code YYYY-MM-DD-Your_post_title.md
          ) will be considered as a blog post and made available at 
          %code http://yoursubdomain.comit.io/YYYY/MM/DD/Your_post_title
          = '. All others files and folders will be just ignored.'

        %ul.menu
          %li 
            = link_to 'An example of post formatted in Markdown'
          %li 
            = link_to 'An example of public Git repository hosting a Comit blog'

        %h2 On Git repository pushes, a Hook Url notify Comit app to refresh its cache

        %p In order for Comit to track new publication or any other modifications on your content, Comit need a way to be alerted when change are pushed on your public Git repository. To archieve that, each blog has a unique "Hook Url" that pull change to the cache when reached. You will need to configure your Git provider to setup a Post-Receive Hooks to this URL. 

        %ul.menu
          %li 
            = link_to 'How-to on Github', 'https://help.github.com/articles/post-receive-hooks'

      = render 'welcome/coming_soon'

      #logo
        #pictures
          = image_tag 'logo_git.png'
          = image_tag 'logo_markdown.png'

  %hr

  / = render 'welcome/pricing'