config/routes.rb
Comit::Application.routes.draw do

  post "early_access/create"

  match     ':year/:month/:day/:title.md' => 'post#markdown'                        # Post in Mardown
  match     ':year/:month/:day/:title'    => 'post#show'                            # Post in HTML
  match     'hook/:token'                 => 'blog#hook',      :via => :post        # Hook for Git repository pull
  match     'auth/:provider/callback'     => 'session#create'                       # Authentication callback for omniauth
  match     'signout'                     => 'session#destroy'                      # Sign out
  match     'user/dashboard'              => 'user#show'                            # User profile
  resources :user,                        only: [:update, :destroy]                 # User management
  resources :blog,                        only: [:create, :destroy, :edit, :update] # Blog management
  root to:  'blog#index'                                                            # Blog index

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :blogs, dependent: :destroy

  attr_accessible :name

  # To activate open registration, uncomment the last part
  def self.from_omniauth(auth)
    where(auth.slice('provider', 'uid')).first #|| create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid      = auth['uid']
      user.name     = auth['info']['name']
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_filter :authenticated?
  
  def show
    @user = current_user
    @blog = Blog.new
  end

  def update
    if current_user.update_attributes(params[:user])
      redirect_to user_dashboard_path
    else
      redirect_to user_dashboard_path
    end
  end

  def destroy
    current_user.destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/helpers/user_helper.rb
module UserHelper

  def top_links_for_dashboard
    links = 'Signed in as '
    links += link_to current_user.name, user_dashboard_path
    links += ". "
    links += link_to "Sign out", signout_path
    return links.html_safe
  end
end

app/views/user/show.haml
- content_for :title do
  = "Comit Dashboard - #{current_user.name}"

= render 'layouts/header', title: "Comit Dashboard", links: top_links_for_dashboard

#dashboard
  #left-panel
    #user
      %p
        Hi 
        %b= "#{current_user.name}, "
        %br
        You have 
        %b= current_user.blogs.count
        blogs hosted on Comit.
        %br
        You are in trial.

      %a#build-form{href: '#'} Build a new blog

      %ul.menu
        %li>
          = link_to 'Contact Comit developer', 'mailto:garnier.etienne@gmail.com'
        - if !@display_form
          %li>
            %a#edit-personnal{href: '#'} Edit my personnal information
          %li>
            %a#delete-my-account{href: '#'} Completly delete my account and my blogs

      #delete-my-account-button
        = link_to "Delete my account and all my blogs", user_path(current_user), method: :delete, confirm: "Are your sure ?"

  #right-panel

    #personnal-information{class: @display_user_form || ''}
      - if !@user.errors.empty?
        %ul.errors
          - @user.errors.each do |attr, error|
            %li<
              %b= attr.capitalize
              = " #{error}"
      = form_for @user do |f|
        .form-box
          %h1
            = f.text_field :name, value: current_user.name
        = f.submit "Save changes !"

    #new-blog{class: @display_blog_form || ''}
      %p 
        For each new blog, you will need an existing public Git repository. 
        = link_to 'Github', 'https://github.com/'
        can provide it for free.
        %br
        This repository root folder will be scanned for markup file using the correct name scheme: 
        %code YYYY-MM-DD-Post_title.md
        , all other files or folders will just be ignored.
        
      - if !@blog.errors.empty?
        %ul.errors
          - @blog.errors.each do |attr, error|
            %li<
              %b= attr.capitalize
              = " #{error}"
      = form_for @blog, url: {controller: 'blog', action: (@blog.new_record? ? 'create' : 'update')} do |f|
        .form-box
          %h1
            = f.text_field :name, value: @blog.name || 'Blog Title'
          %dl
            %dt= f.label :subdomain, 'Subdomain'
            %dd
              = f.text_field :subdomain
              = ".#{request.host}"
            %dt= f.label :git, 'Git URL'
            %dd= f.text_field :git
        = f.submit (@blog.new_record? ? "Put online !" : "Save changes !")

    - current_user.blogs.order("created_at DESC").each do |blog|
      .blog
        %h1= blog.name
        %dl
          %dt URL
          %dd= link_to url_for_subdomain(blog.subdomain), url_for_subdomain(blog.subdomain)
          %dt Git URL
          %dd= link_to blog.git, blog.git
          %dt 
            Hook URL (POST)
            = link_to '?', "http://help.comit.dev:3000/2013/01/15/Hook_URL"
          %dd 
            %code=url_for_token(blog.token)
        %hr
        %ul.menu
          %li>
            = link_to 'Edit', edit_blog_path(blog)
          %li>
            = link_to 'Delete', blog_path(blog), method: :delete, confirm: "Are your sure you want to delete this blog (#{blog.name}) ?"